from __future__ import annotations

from typing import Any, overload

from sage.structure.element import EuclideanDomainElement, RingElement

class Integer(EuclideanDomainElement):

    def __init__(self, x=None, base=0): ...

    def hash_c(self) -> int:
        ...

    def __pari__(self) -> object:
        ...

    def _shift_helper(self, y: object, sign: int) -> object:
        ...

    def _add_(self, other: object) -> object:
        ...

    def _mul_(self, other: object) -> object:
        ...

    def _pow_(self, other: object) -> object:
        ...

    def _and(self, other: Integer) -> Integer:
        ...

    def _or(self, other: Integer) -> Integer:
        ...

    def _xor(self, other: Integer) -> Integer:
        ...

    def _exact_log_log2_iter(self, m: Integer) -> int:
        ...

    def _exact_log_mpfi_log(self, m: object) -> int:
        ...

    def _valuation(self, p: Integer) -> RingElement:
        ...

    def _val_unit(self, p: Integer) -> object:
        ...

    def _divide_knowing_divisible_by(self, right: Integer) -> Integer:
        ...

    def _is_power_of(self, n: Integer) -> bool:
        ...

    def _pseudoprime_is_prime(self, proof: object) -> bool:
        ...

    @overload
    def __add__(self, other: Int) -> Integer: ...

    @overload
    def __add__(self, other: Any) -> Any: ...

    @overload
    def __sub__(self, other: Int) -> Integer: ...

    @overload
    def __sub__(self, other: Any) -> Any: ...

    @overload
    def __rsub__(self, other: int) -> Integer: ...

    @overload
    def __rsub__(self, other: Any) -> Any: ...

    @overload
    def __radd__(self, other: int) -> Integer: ...

    @overload
    def __radd__(self, other: Any) -> Any: ...

    @overload
    def __mul__(self, other: Int) -> Integer: ...

    @overload
    def __mul__(self, other: Any) -> Any: ...

    @overload
    def __rmul__(self, other: int) -> Integer: ...

    @overload
    def __rmul__(self, other: Any) -> Any: ...

    @overload
    def __pow__(self, other: Int) -> Integer: ...

    @overload
    def __pow__(self, other: Int, modulo: Int | None) -> Integer: ...

    @overload
    def __pow__(self, other: Any, modulo: Any) -> Any: ...

Int = Integer | int

_small_primes_table: list[bool]
