from typing import overload

from sage.structure.element import EuclideanDomainElement, RingElement

class Integer(EuclideanDomainElement):
    def __init__(self, x: object = None, base: Int = 0) -> None: ...
    def __pari__(self) -> object: ...
    def _shift_helper(self, y: object, sign: int) -> object: ...
    def _add_(self, other: object) -> object: ...
    def _mul_(self, other: object) -> object: ...
    def _pow_(self, other: object) -> object: ...
    def _exact_log_log2_iter(self, m: Integer) -> int: ...
    def _exact_log_mpfi_log(self, m: object) -> int: ...
    def _valuation(self, p: Integer) -> RingElement: ...
    def valuation(self, p: Int) -> RingElement: ...

    ord = valuation

    def val_unit(self, p: Int) -> object: ...
    def divide_knowing_divisible_by(self, right: Int) -> Integer: ...
    def is_power_of(self, n: Integer) -> bool: ...
    def is_pseudoprime(self) -> bool: ...
    @overload
    def __add__(self, other: Int) -> Integer: ...
    @overload
    def __add__(self, other: object) -> object: ...
    @overload
    def __sub__(self, other: Int) -> Integer: ...
    @overload
    def __sub__(self, other: object) -> object: ...
    @overload
    def __rsub__(self, other: int) -> Integer: ...
    @overload
    def __rsub__(self, other: object) -> object: ...
    @overload
    def __radd__(self, other: int) -> Integer: ...
    @overload
    def __radd__(self, other: object) -> object: ...
    @overload
    def __mul__(self, other: Int) -> Integer: ...
    @overload
    def __mul__(self, other: object) -> object: ...
    @overload
    def __rmul__(self, other: int) -> Integer: ...
    @overload
    def __rmul__(self, other: object) -> object: ...
    @overload
    def __pow__(self, other: Int) -> Integer: ...
    @overload
    def __pow__(self, other: Int, modulo: Int | None) -> Integer: ...
    @overload
    def __pow__(self, other: object, modulo: object | None) -> object: ...

# This type alias is not available at runtime
type Int = Integer | int
