from sage.structure.sage_object import SageObject

class Element(SageObject):
    def __add__(self, other): ...

    def __sub__(self, other): ...

    def __neg__(self): ...

    def __mul__(self, other): ...

    def __matmul__(self, other): ...

    def __truediv__(self, other): ...

    def __floordiv__(self, other): ...

    def __mod__(self, other): ...

    def __pow__(self, other, modulo): ...

class ElementWithCachedMethod(Element):
    ...

class ModuleElement(Element):
    ...

class ModuleElementWithMutability(ModuleElement):
    ...

class MonoidElement(Element):
    ...

class AdditiveGroupElement(ModuleElement):
    ...

class MultiplicativeGroupElement(MonoidElement):
    ...

class RingElement(ModuleElement):
    ...

class CommutativeRingElement(RingElement):
    ...

class Expression(CommutativeRingElement):
    ...

class Vector(ModuleElementWithMutability):
    ...

class Matrix(ModuleElement):
    ...

class IntegralDomainElement(CommutativeRingElement):
    ...

class DedekindDomainElement(IntegralDomainElement):
    ...

class PrincipalIdealDomainElement(DedekindDomainElement):
    ...

class EuclideanDomainElement(PrincipalIdealDomainElement):
    ...

class FieldElement(CommutativeRingElement):
    ...

class AlgebraElement(RingElement):
    ...

class CommutativeAlgebraElement(CommutativeRingElement):
    ...

class InfinityElement(RingElement):
    ...
